List<String> mesFruitAll = [
  "",
  "Ananas",
  "Avocat",
  "Baie de goji",
  "Banane",
  "Bergamote",
  "Carambole",
  "Cassis",
  "Cerise",
  "Citron",
  "Cranberry",
  "Fraise",
  "Fruit de la passion",
  "Fruit du dragon",
  "Grenade",
  "Kaki",
  "Kiwaï",
  "Kiwi",
  "Kumquat",
  "Litchi",
  "Noix de coco",
  "Orange",
  "Pain de singe",
  "Poire",
  "Pomme"
];
List<String> mesFruitAz = [
  "",
  "Abricot",
  "Abricot pays",
  "Açaï",
  "Acérola",
  "Achacha",
  "Aguaje",
  "Airelle rouge",
  "Amla",
  "Ananas",
  "Arbouse",
  "Aronia",
  "Aronia noir",
  "Aronia rouge",
  "Asiminier trilobé",
  "Atte",
  "Avocat",
  "Awara",
  "Babaco",
  "Bael",
  "Baie de goji",
  "Baies d'argousier",
  "Banane",
  "Banane sauvage",
  "Barbadine",
  "Bergamote",
  "Bigarade",
  "Bignay",
  "Bilimbi",
  "Cacao",
  "Calamondin",
  "Canistel",
  "Carambole",
  "Cassis",
  "Cédrat",
  "Cempedak",
  "Cenelle",
  "Cerise",
  "Cerisier de Cayenne",
  "Cerisier du Brésil",
  "Chérimole",
  "Chèvrefeuille bleu",
  "Citron",
  "Citron doux",
  "Citron vert",
  "Cocona",
  "Cur de buf",
  "Coing",
  "Combava",
  "Corossol",
  "Cranberry",
  "Cynorhodon",
  "Datte",
  "Durian",
  "Feijoas",
  "Figue",
  "Figue de Barbarie",
  "Fraise",
  "Fraise chinoise",
  "Framboise",
  "Fruit à pain",
  "Fruit de la passion",
  "Fruit du dragon",
  "Fruit miracle",
  "Goumi du Japon",
  "Goyave",
  "Goyave de Chine",
  "Grenade",
  "Grenadelle",
  "Griottes",
  "Groseille",
  "Groseiller des Barbades",
  "Icaque",
  "Jaboticaba",
  "Jacque",
  "Jagua",
  "Jamalac",
  "Jamblon",
  "Jujube",
  "Kaki",
  "Kiwaï",
  "Kiwano",
  "Kiwi",
  "Kumquat",
  "Litchi",
  "Longane",
  "Longkong",
  "Luo han Guo",
  "Main de Bouddha",
  "Mandarine",
  "Mangoustan",
  "Mangue",
  "Melon",
  "Micocoule",
  "Mikan",
  "Mirabelle",
  "Mûre",
  "Mûrier blanc",
  "Mûrier noir",
  "Mûrier rouge",
  "Myrobolan",
  "Myrtille",
  "Narangille",
  "Nashi",
  "Nèfle",
  "Nèfle du Japon",
  "Noix de bétel",
  "Noix de coco",
  "Nono",
  "Olive",
  "Orange",
  "Pain de singe",
  "Palmier pêche",
  "Papaye",
  "Pastèque",
  "Pêche",
  "Pepino",
  "Phalsa",
  "Physalis",
  "Poire",
  "Pomme",
  "Pomme de cajou",
  "Pomme de lait",
  "Pomme étoile blanche",
  "Pomme malacca",
  "Prune",
  "Prune de Cythère",
  "Prune du Natal",
  "Prune mombin",
  "Quenette",
  "Raisin",
  "Raisinier bord de mer",
  "Ramboutan",
  "Reine-Claude",
  "Roselle",
  "Safou",
  "Salak",
  "Sapote",
  "Sapote blanche",
  "Sapotier noir",
  "Sapotille",
  "Sureau",
  "Taal",
  "Tamarin",
  "Tomate en arbre",
  "Tomatille",
  "Vavangue",
  "Wampi"
];
